#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SleepingBus_Android.Resource", IsApplication=true)]

namespace SleepingBus_Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ADD4 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int budi = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int AddBtn = 2131034117;
			
			// aapt resource value: 0x7f050009
			public const int BtnDistance = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int BtnRepeats = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int BtnSound = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int CbVibration = 2131034124;
			
			// aapt resource value: 0x7f050002
			public const int LRLayout = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int LinerLBottom = 2131034116;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout1 = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int linearLayoutMain = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int listView = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int scrollView1 = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int searchView = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int tVNewAlarm = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int NewAlarm = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int Distance = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int NewAlarm = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int Repeats = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int Sound = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int Vibration = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
